theme: jekyll-theme-architect
title: [Anirban Chakraborty]
description: [I am a PhD student at the University of Southern California in the department of Data Sciences and Operations housed in the Marshall School of Business]
